// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
import GoogleCloudWKT
import GoogleCloudGax

extension Clients {
  protocol EnterpriseKnowledgeGraphServiceStub: Sendable {
    func createEntityReconciliationJob(
      request: CreateEntityReconciliationJobRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudEnterpriseKnowledgeGraphV1.EntityReconciliationJob

    func getEntityReconciliationJob(
      request: GetEntityReconciliationJobRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudEnterpriseKnowledgeGraphV1.EntityReconciliationJob

    func listEntityReconciliationJobs(
      request: ListEntityReconciliationJobsRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudEnterpriseKnowledgeGraphV1.ListEntityReconciliationJobsResponse

    func cancelEntityReconciliationJob(
      request: CancelEntityReconciliationJobRequest, options: GoogleCloudGax.RequestOptions
    ) async throws

    func deleteEntityReconciliationJob(
      request: DeleteEntityReconciliationJobRequest, options: GoogleCloudGax.RequestOptions
    ) async throws

    func lookup(
      request: LookupRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudEnterpriseKnowledgeGraphV1.LookupResponse

    func search(
      request: SearchRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudEnterpriseKnowledgeGraphV1.SearchResponse

    func lookupPublicKg(
      request: LookupPublicKgRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudEnterpriseKnowledgeGraphV1.LookupPublicKgResponse

    func searchPublicKg(
      request: SearchPublicKgRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudEnterpriseKnowledgeGraphV1.SearchPublicKgResponse
  }
}
