// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
#if canImport(FoundationNetworking)
  import FoundationNetworking
#endif
import GoogleCloudWKT
import GoogleCloudGax

/// APIs for enterprise knowledge graph product.
///
/// @Snippet(path: "EnterpriseKnowledgeGraphServiceQuickstart")
public final class EnterpriseKnowledgeGraphServiceClient: Clients
    .EnterpriseKnowledgeGraphServiceProtocol, Sendable
{
  let inner: any Clients.EnterpriseKnowledgeGraphServiceStub

  /// Creates a new `EnterpriseKnowledgeGraphServiceClient` instance.
  public init(_ options: GoogleCloudGax.ClientOptions = .init()) throws {
    var inner: any Clients.EnterpriseKnowledgeGraphServiceStub =
      try Clients.EnterpriseKnowledgeGraphServiceTransport(options)
    inner = Clients.EnterpriseKnowledgeGraphServiceRetry(inner, options: options)
    if let logger = options.logger {
      inner = Clients.EnterpriseKnowledgeGraphServiceLogging(inner, logger: logger)
    }
    self.inner = inner
  }

  /// Creates a EntityReconciliationJob. A EntityReconciliationJob once created
  /// will right away be attempted to start.
  ///
  /// @Snippet(path: "EnterpriseKnowledgeGraphService_CreateEntityReconciliationJob")
  public func createEntityReconciliationJob(
    request: CreateEntityReconciliationJobRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleCloudEnterpriseKnowledgeGraphV1.EntityReconciliationJob {
    try await self.inner.createEntityReconciliationJob(request: request, options: options)
  }

  /// Gets a EntityReconciliationJob.
  ///
  /// @Snippet(path: "EnterpriseKnowledgeGraphService_GetEntityReconciliationJob")
  public func getEntityReconciliationJob(
    request: GetEntityReconciliationJobRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleCloudEnterpriseKnowledgeGraphV1.EntityReconciliationJob {
    try await self.inner.getEntityReconciliationJob(request: request, options: options)
  }

  /// Lists Entity Reconciliation Jobs.
  ///
  /// @Snippet(path: "EnterpriseKnowledgeGraphService_ListEntityReconciliationJobs")
  public func listEntityReconciliationJobs(
    request: ListEntityReconciliationJobsRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleCloudEnterpriseKnowledgeGraphV1.ListEntityReconciliationJobsResponse {
    try await self.inner.listEntityReconciliationJobs(request: request, options: options)
  }

  /// Lists Entity Reconciliation Jobs.
  ///
  /// @Snippet(path: "EnterpriseKnowledgeGraphService_ListEntityReconciliationJobs")
  public func listEntityReconciliationJobs(
    byItem: ListEntityReconciliationJobsRequest, options: GoogleCloudGax.RequestOptions
  ) throws -> any AsyncSequence<EntityReconciliationJob, Swift.Error> {
    let listRpc = {
      (token: Swift.String) async throws
        -> GoogleCloudEnterpriseKnowledgeGraphV1.ListEntityReconciliationJobsResponse in
      var request = byItem
      request.pageToken = token
      return try await self.listEntityReconciliationJobs(request: request, options: options)
    }
    return GoogleCloudGax.PaginatedResponseSequence(listRpc: listRpc)
  }

  /// Cancels a EntityReconciliationJob. Success of cancellation is not
  /// guaranteed.
  ///
  /// @Snippet(path: "EnterpriseKnowledgeGraphService_CancelEntityReconciliationJob")
  public func cancelEntityReconciliationJob(
    request: CancelEntityReconciliationJobRequest, options: GoogleCloudGax.RequestOptions
  ) async throws {
    try await self.inner.cancelEntityReconciliationJob(request: request, options: options)
  }

  /// Deletes a EntityReconciliationJob.
  /// It only deletes the job when the job state is in FAILED, SUCCEEDED, and
  /// CANCELLED.
  ///
  /// @Snippet(path: "EnterpriseKnowledgeGraphService_DeleteEntityReconciliationJob")
  public func deleteEntityReconciliationJob(
    request: DeleteEntityReconciliationJobRequest, options: GoogleCloudGax.RequestOptions
  ) async throws {
    try await self.inner.deleteEntityReconciliationJob(request: request, options: options)
  }

  /// Finds the Cloud KG entities with CKG ID(s).
  ///
  /// @Snippet(path: "EnterpriseKnowledgeGraphService_Lookup")
  public func lookup(
    request: LookupRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleCloudEnterpriseKnowledgeGraphV1.LookupResponse {
    try await self.inner.lookup(request: request, options: options)
  }

  /// Searches the Cloud KG entities with entity name.
  ///
  /// @Snippet(path: "EnterpriseKnowledgeGraphService_Search")
  public func search(
    request: SearchRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleCloudEnterpriseKnowledgeGraphV1.SearchResponse {
    try await self.inner.search(request: request, options: options)
  }

  /// Finds the public KG entities with public KG ID(s).
  ///
  /// @Snippet(path: "EnterpriseKnowledgeGraphService_LookupPublicKg")
  public func lookupPublicKg(
    request: LookupPublicKgRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleCloudEnterpriseKnowledgeGraphV1.LookupPublicKgResponse {
    try await self.inner.lookupPublicKg(request: request, options: options)
  }

  /// Searches the public KG entities with entity name.
  ///
  /// @Snippet(path: "EnterpriseKnowledgeGraphService_SearchPublicKg")
  public func searchPublicKg(
    request: SearchPublicKgRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleCloudEnterpriseKnowledgeGraphV1.SearchPublicKgResponse {
    try await self.inner.searchPublicKg(request: request, options: options)
  }
}

extension Clients {
  /// A Swift protocol to mock `EnterpriseKnowledgeGraphServiceClient`.
  ///
  /// To mock `EnterpriseKnowledgeGraphServiceClient` change your functions to receive
  /// `some EnterpriseKnowledgeGraphServiceProtocol` or `any EnterpriseKnowledgeGraphServiceProtocol`
  /// and pass a mock implementation in your tests.
  public protocol EnterpriseKnowledgeGraphServiceProtocol {
    /// See `EnterpriseKnowledgeGraphServiceClient.createEntityReconciliationJob`.
    func createEntityReconciliationJob(request: CreateEntityReconciliationJobRequest) async throws
      -> GoogleCloudEnterpriseKnowledgeGraphV1.EntityReconciliationJob

    /// See `EnterpriseKnowledgeGraphServiceClient.createEntityReconciliationJob`.
    func createEntityReconciliationJob(
      parent: Swift.String,
      entityReconciliationJob: EntityReconciliationJob?,
    ) async throws -> GoogleCloudEnterpriseKnowledgeGraphV1.EntityReconciliationJob

    /// See `EnterpriseKnowledgeGraphServiceClient.getEntityReconciliationJob`.
    func getEntityReconciliationJob(request: GetEntityReconciliationJobRequest) async throws
      -> GoogleCloudEnterpriseKnowledgeGraphV1.EntityReconciliationJob

    /// See `EnterpriseKnowledgeGraphServiceClient.getEntityReconciliationJob`.
    func getEntityReconciliationJob(
      name: Swift.String,
    ) async throws -> GoogleCloudEnterpriseKnowledgeGraphV1.EntityReconciliationJob

    /// See `EnterpriseKnowledgeGraphServiceClient.listEntityReconciliationJobs`.
    func listEntityReconciliationJobs(request: ListEntityReconciliationJobsRequest) async throws
      -> GoogleCloudEnterpriseKnowledgeGraphV1.ListEntityReconciliationJobsResponse

    /// See `EnterpriseKnowledgeGraphServiceClient.listEntityReconciliationJobs`.
    func listEntityReconciliationJobs(
      byItem: ListEntityReconciliationJobsRequest
    ) throws -> any AsyncSequence<EntityReconciliationJob, Swift.Error>

    /// See `EnterpriseKnowledgeGraphServiceClient.listEntityReconciliationJobs`.
    func listEntityReconciliationJobs(
      parent: Swift.String,
    ) throws -> any AsyncSequence<EntityReconciliationJob, Swift.Error>

    /// See `EnterpriseKnowledgeGraphServiceClient.cancelEntityReconciliationJob`.
    func cancelEntityReconciliationJob(request: CancelEntityReconciliationJobRequest) async throws

    /// See `EnterpriseKnowledgeGraphServiceClient.cancelEntityReconciliationJob`.
    func cancelEntityReconciliationJob(
      name: Swift.String,
    ) async throws

    /// See `EnterpriseKnowledgeGraphServiceClient.deleteEntityReconciliationJob`.
    func deleteEntityReconciliationJob(request: DeleteEntityReconciliationJobRequest) async throws

    /// See `EnterpriseKnowledgeGraphServiceClient.deleteEntityReconciliationJob`.
    func deleteEntityReconciliationJob(
      name: Swift.String,
    ) async throws

    /// See `EnterpriseKnowledgeGraphServiceClient.lookup`.
    func lookup(request: LookupRequest) async throws
      -> GoogleCloudEnterpriseKnowledgeGraphV1.LookupResponse

    /// See `EnterpriseKnowledgeGraphServiceClient.lookup`.
    func lookup(
      parent: Swift.String,
      ids: [Swift.String],
    ) async throws -> GoogleCloudEnterpriseKnowledgeGraphV1.LookupResponse

    /// See `EnterpriseKnowledgeGraphServiceClient.search`.
    func search(request: SearchRequest) async throws
      -> GoogleCloudEnterpriseKnowledgeGraphV1.SearchResponse

    /// See `EnterpriseKnowledgeGraphServiceClient.search`.
    func search(
      parent: Swift.String,
      query: Swift.String,
    ) async throws -> GoogleCloudEnterpriseKnowledgeGraphV1.SearchResponse

    /// See `EnterpriseKnowledgeGraphServiceClient.lookupPublicKg`.
    func lookupPublicKg(request: LookupPublicKgRequest) async throws
      -> GoogleCloudEnterpriseKnowledgeGraphV1.LookupPublicKgResponse

    /// See `EnterpriseKnowledgeGraphServiceClient.lookupPublicKg`.
    func lookupPublicKg(
      parent: Swift.String,
      ids: [Swift.String],
    ) async throws -> GoogleCloudEnterpriseKnowledgeGraphV1.LookupPublicKgResponse

    /// See `EnterpriseKnowledgeGraphServiceClient.searchPublicKg`.
    func searchPublicKg(request: SearchPublicKgRequest) async throws
      -> GoogleCloudEnterpriseKnowledgeGraphV1.SearchPublicKgResponse

    /// See `EnterpriseKnowledgeGraphServiceClient.searchPublicKg`.
    func searchPublicKg(
      parent: Swift.String,
      query: Swift.String,
    ) async throws -> GoogleCloudEnterpriseKnowledgeGraphV1.SearchPublicKgResponse

    /// See `EnterpriseKnowledgeGraphServiceClient.createEntityReconciliationJob`.
    func createEntityReconciliationJob(
      request: CreateEntityReconciliationJobRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudEnterpriseKnowledgeGraphV1.EntityReconciliationJob

    /// See `EnterpriseKnowledgeGraphServiceClient.getEntityReconciliationJob`.
    func getEntityReconciliationJob(
      request: GetEntityReconciliationJobRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudEnterpriseKnowledgeGraphV1.EntityReconciliationJob

    /// See `EnterpriseKnowledgeGraphServiceClient.listEntityReconciliationJobs`.
    func listEntityReconciliationJobs(
      request: ListEntityReconciliationJobsRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudEnterpriseKnowledgeGraphV1.ListEntityReconciliationJobsResponse

    /// See `EnterpriseKnowledgeGraphServiceClient.listEntityReconciliationJobs`.
    func listEntityReconciliationJobs(
      byItem: ListEntityReconciliationJobsRequest, options: GoogleCloudGax.RequestOptions
    ) throws -> any AsyncSequence<EntityReconciliationJob, Swift.Error>

    /// See `EnterpriseKnowledgeGraphServiceClient.cancelEntityReconciliationJob`.
    func cancelEntityReconciliationJob(
      request: CancelEntityReconciliationJobRequest, options: GoogleCloudGax.RequestOptions
    ) async throws

    /// See `EnterpriseKnowledgeGraphServiceClient.deleteEntityReconciliationJob`.
    func deleteEntityReconciliationJob(
      request: DeleteEntityReconciliationJobRequest, options: GoogleCloudGax.RequestOptions
    ) async throws

    /// See `EnterpriseKnowledgeGraphServiceClient.lookup`.
    func lookup(
      request: LookupRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudEnterpriseKnowledgeGraphV1.LookupResponse

    /// See `EnterpriseKnowledgeGraphServiceClient.search`.
    func search(
      request: SearchRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudEnterpriseKnowledgeGraphV1.SearchResponse

    /// See `EnterpriseKnowledgeGraphServiceClient.lookupPublicKg`.
    func lookupPublicKg(
      request: LookupPublicKgRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudEnterpriseKnowledgeGraphV1.LookupPublicKgResponse

    /// See `EnterpriseKnowledgeGraphServiceClient.searchPublicKg`.
    func searchPublicKg(
      request: SearchPublicKgRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudEnterpriseKnowledgeGraphV1.SearchPublicKgResponse
  }
}

// Default implementations
extension Clients.EnterpriseKnowledgeGraphServiceProtocol {
  public func createEntityReconciliationJob(request: CreateEntityReconciliationJobRequest)
    async throws -> GoogleCloudEnterpriseKnowledgeGraphV1.EntityReconciliationJob
  {
    try await self.createEntityReconciliationJob(request: request, options: .init())
  }

  public func createEntityReconciliationJob(
    request: CreateEntityReconciliationJobRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleCloudEnterpriseKnowledgeGraphV1.EntityReconciliationJob {
    throw GoogleCloudGax.RequestError.unimplemented
  }

  public func createEntityReconciliationJob(
    parent: Swift.String,
    entityReconciliationJob: EntityReconciliationJob?,
  ) async throws -> GoogleCloudEnterpriseKnowledgeGraphV1.EntityReconciliationJob {
    let request = CreateEntityReconciliationJobRequest().with {
      $0.parent = parent
      $0.entityReconciliationJob = entityReconciliationJob
    }
    return try await self.createEntityReconciliationJob(request: request)
  }

  public func getEntityReconciliationJob(request: GetEntityReconciliationJobRequest) async throws
    -> GoogleCloudEnterpriseKnowledgeGraphV1.EntityReconciliationJob
  {
    try await self.getEntityReconciliationJob(request: request, options: .init())
  }

  public func getEntityReconciliationJob(
    request: GetEntityReconciliationJobRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleCloudEnterpriseKnowledgeGraphV1.EntityReconciliationJob {
    throw GoogleCloudGax.RequestError.unimplemented
  }

  public func getEntityReconciliationJob(
    name: Swift.String,
  ) async throws -> GoogleCloudEnterpriseKnowledgeGraphV1.EntityReconciliationJob {
    let request = GetEntityReconciliationJobRequest().with {
      $0.name = name
    }
    return try await self.getEntityReconciliationJob(request: request)
  }

  public func listEntityReconciliationJobs(request: ListEntityReconciliationJobsRequest)
    async throws -> GoogleCloudEnterpriseKnowledgeGraphV1.ListEntityReconciliationJobsResponse
  {
    try await self.listEntityReconciliationJobs(request: request, options: .init())
  }

  public func listEntityReconciliationJobs(
    request: ListEntityReconciliationJobsRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleCloudEnterpriseKnowledgeGraphV1.ListEntityReconciliationJobsResponse {
    throw GoogleCloudGax.RequestError.unimplemented
  }

  public func listEntityReconciliationJobs(
    byItem: ListEntityReconciliationJobsRequest
  ) throws -> any AsyncSequence<EntityReconciliationJob, Swift.Error> {
    try self.listEntityReconciliationJobs(byItem: byItem, options: .init())
  }

  public func listEntityReconciliationJobs(
    byItem: ListEntityReconciliationJobsRequest, options: GoogleCloudGax.RequestOptions
  ) throws -> any AsyncSequence<EntityReconciliationJob, Swift.Error> {
    let listRpc = {
      (token: Swift.String) async throws
        -> GoogleCloudEnterpriseKnowledgeGraphV1.ListEntityReconciliationJobsResponse in
      throw GoogleCloudGax.RequestError.unimplemented
    }
    return GoogleCloudGax.PaginatedResponseSequence(listRpc: listRpc)
  }

  public func listEntityReconciliationJobs(
    parent: Swift.String,
  ) throws -> any AsyncSequence<EntityReconciliationJob, Swift.Error> {
    let request = ListEntityReconciliationJobsRequest().with {
      $0.parent = parent
    }
    return try self.listEntityReconciliationJobs(byItem: request)
  }

  public func cancelEntityReconciliationJob(request: CancelEntityReconciliationJobRequest)
    async throws
  {
    try await self.cancelEntityReconciliationJob(request: request, options: .init())
  }

  public func cancelEntityReconciliationJob(
    request: CancelEntityReconciliationJobRequest, options: GoogleCloudGax.RequestOptions
  ) async throws {
    throw GoogleCloudGax.RequestError.unimplemented
  }

  public func cancelEntityReconciliationJob(
    name: Swift.String,
  ) async throws {
    let request = CancelEntityReconciliationJobRequest().with {
      $0.name = name
    }
    try await self.cancelEntityReconciliationJob(request: request)
  }

  public func deleteEntityReconciliationJob(request: DeleteEntityReconciliationJobRequest)
    async throws
  {
    try await self.deleteEntityReconciliationJob(request: request, options: .init())
  }

  public func deleteEntityReconciliationJob(
    request: DeleteEntityReconciliationJobRequest, options: GoogleCloudGax.RequestOptions
  ) async throws {
    throw GoogleCloudGax.RequestError.unimplemented
  }

  public func deleteEntityReconciliationJob(
    name: Swift.String,
  ) async throws {
    let request = DeleteEntityReconciliationJobRequest().with {
      $0.name = name
    }
    try await self.deleteEntityReconciliationJob(request: request)
  }

  public func lookup(request: LookupRequest) async throws
    -> GoogleCloudEnterpriseKnowledgeGraphV1.LookupResponse
  {
    try await self.lookup(request: request, options: .init())
  }

  public func lookup(
    request: LookupRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleCloudEnterpriseKnowledgeGraphV1.LookupResponse {
    throw GoogleCloudGax.RequestError.unimplemented
  }

  public func lookup(
    parent: Swift.String,
    ids: [Swift.String],
  ) async throws -> GoogleCloudEnterpriseKnowledgeGraphV1.LookupResponse {
    let request = LookupRequest().with {
      $0.parent = parent
      $0.ids = ids
    }
    return try await self.lookup(request: request)
  }

  public func search(request: SearchRequest) async throws
    -> GoogleCloudEnterpriseKnowledgeGraphV1.SearchResponse
  {
    try await self.search(request: request, options: .init())
  }

  public func search(
    request: SearchRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleCloudEnterpriseKnowledgeGraphV1.SearchResponse {
    throw GoogleCloudGax.RequestError.unimplemented
  }

  public func search(
    parent: Swift.String,
    query: Swift.String,
  ) async throws -> GoogleCloudEnterpriseKnowledgeGraphV1.SearchResponse {
    let request = SearchRequest().with {
      $0.parent = parent
      $0.query = query
    }
    return try await self.search(request: request)
  }

  public func lookupPublicKg(request: LookupPublicKgRequest) async throws
    -> GoogleCloudEnterpriseKnowledgeGraphV1.LookupPublicKgResponse
  {
    try await self.lookupPublicKg(request: request, options: .init())
  }

  public func lookupPublicKg(
    request: LookupPublicKgRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleCloudEnterpriseKnowledgeGraphV1.LookupPublicKgResponse {
    throw GoogleCloudGax.RequestError.unimplemented
  }

  public func lookupPublicKg(
    parent: Swift.String,
    ids: [Swift.String],
  ) async throws -> GoogleCloudEnterpriseKnowledgeGraphV1.LookupPublicKgResponse {
    let request = LookupPublicKgRequest().with {
      $0.parent = parent
      $0.ids = ids
    }
    return try await self.lookupPublicKg(request: request)
  }

  public func searchPublicKg(request: SearchPublicKgRequest) async throws
    -> GoogleCloudEnterpriseKnowledgeGraphV1.SearchPublicKgResponse
  {
    try await self.searchPublicKg(request: request, options: .init())
  }

  public func searchPublicKg(
    request: SearchPublicKgRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleCloudEnterpriseKnowledgeGraphV1.SearchPublicKgResponse {
    throw GoogleCloudGax.RequestError.unimplemented
  }

  public func searchPublicKg(
    parent: Swift.String,
    query: Swift.String,
  ) async throws -> GoogleCloudEnterpriseKnowledgeGraphV1.SearchPublicKgResponse {
    let request = SearchPublicKgRequest().with {
      $0.parent = parent
      $0.query = query
    }
    return try await self.searchPublicKg(request: request)
  }
}
