// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
#if canImport(FoundationNetworking)
  import FoundationNetworking
#endif
import GoogleCloudWkt
import GoogleCloudGax

extension Clients {
  final class EnterpriseKnowledgeGraphServiceRetry: EnterpriseKnowledgeGraphServiceStub {
    let inner: any EnterpriseKnowledgeGraphServiceStub
    let options: GoogleCloudGax.ClientOptions

    public init(
      _ inner: any EnterpriseKnowledgeGraphServiceStub, options: GoogleCloudGax.ClientOptions
    ) {
      self.inner = inner
      self.options = options
    }

    func _intercept<Input, Output>(
      request: Input,
      options: GoogleCloudGax.RequestOptions,
      idempotent: Swift.Bool,
      action: (Input, GoogleCloudGax.RequestOptions) async throws -> Output,
    ) async throws -> Output {
      let loop = GoogleCloudGax._RetryLoop(
        options: options, withDefault: self.options, idempotent: idempotent,
      )
      let attempt = { (attemptTimeout: Swift.Duration?) async throws -> Output in
        var attemptOptions = options
        attemptOptions.attemptTimeout = attemptTimeout
        return try await action(request, attemptOptions)
      }
      return try await loop.run(attempt: attempt)
    }

    public func createEntityReconciliationJob(
      request: CreateEntityReconciliationJobRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudEnterpriseKnowledgeGraphV1.EntityReconciliationJob {
      try await self._intercept(
        request: request,
        options: options,
        idempotent: false,
        action: {
          (r: CreateEntityReconciliationJobRequest, o: GoogleCloudGax.RequestOptions) async throws
            -> GoogleCloudEnterpriseKnowledgeGraphV1.EntityReconciliationJob
          in
          return try await self.inner.createEntityReconciliationJob(request: r, options: o)
        })
    }

    public func getEntityReconciliationJob(
      request: GetEntityReconciliationJobRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudEnterpriseKnowledgeGraphV1.EntityReconciliationJob {
      try await self._intercept(
        request: request,
        options: options,
        idempotent: true,
        action: {
          (r: GetEntityReconciliationJobRequest, o: GoogleCloudGax.RequestOptions) async throws
            -> GoogleCloudEnterpriseKnowledgeGraphV1.EntityReconciliationJob
          in
          return try await self.inner.getEntityReconciliationJob(request: r, options: o)
        })
    }

    public func listEntityReconciliationJobs(
      request: ListEntityReconciliationJobsRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudEnterpriseKnowledgeGraphV1.ListEntityReconciliationJobsResponse {
      try await self._intercept(
        request: request,
        options: options,
        idempotent: true,
        action: {
          (r: ListEntityReconciliationJobsRequest, o: GoogleCloudGax.RequestOptions) async throws
            -> GoogleCloudEnterpriseKnowledgeGraphV1.ListEntityReconciliationJobsResponse
          in
          return try await self.inner.listEntityReconciliationJobs(request: r, options: o)
        })
    }

    public func cancelEntityReconciliationJob(
      request: CancelEntityReconciliationJobRequest, options: GoogleCloudGax.RequestOptions
    ) async throws {
      try await self._intercept(
        request: request,
        options: options,
        idempotent: false,
        action: {
          (r: CancelEntityReconciliationJobRequest, o: GoogleCloudGax.RequestOptions) async throws
            -> Void in
          return try await self.inner.cancelEntityReconciliationJob(request: r, options: o)
        })
    }

    public func deleteEntityReconciliationJob(
      request: DeleteEntityReconciliationJobRequest, options: GoogleCloudGax.RequestOptions
    ) async throws {
      try await self._intercept(
        request: request,
        options: options,
        idempotent: false,
        action: {
          (r: DeleteEntityReconciliationJobRequest, o: GoogleCloudGax.RequestOptions) async throws
            -> Void in
          return try await self.inner.deleteEntityReconciliationJob(request: r, options: o)
        })
    }

    public func lookup(
      request: LookupRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudEnterpriseKnowledgeGraphV1.LookupResponse {
      try await self._intercept(
        request: request,
        options: options,
        idempotent: true,
        action: {
          (r: LookupRequest, o: GoogleCloudGax.RequestOptions) async throws
            -> GoogleCloudEnterpriseKnowledgeGraphV1.LookupResponse
          in
          return try await self.inner.lookup(request: r, options: o)
        })
    }

    public func search(
      request: SearchRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudEnterpriseKnowledgeGraphV1.SearchResponse {
      try await self._intercept(
        request: request,
        options: options,
        idempotent: true,
        action: {
          (r: SearchRequest, o: GoogleCloudGax.RequestOptions) async throws
            -> GoogleCloudEnterpriseKnowledgeGraphV1.SearchResponse
          in
          return try await self.inner.search(request: r, options: o)
        })
    }

    public func lookupPublicKg(
      request: LookupPublicKgRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudEnterpriseKnowledgeGraphV1.LookupPublicKgResponse {
      try await self._intercept(
        request: request,
        options: options,
        idempotent: true,
        action: {
          (r: LookupPublicKgRequest, o: GoogleCloudGax.RequestOptions) async throws
            -> GoogleCloudEnterpriseKnowledgeGraphV1.LookupPublicKgResponse
          in
          return try await self.inner.lookupPublicKg(request: r, options: o)
        })
    }

    public func searchPublicKg(
      request: SearchPublicKgRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudEnterpriseKnowledgeGraphV1.SearchPublicKgResponse {
      try await self._intercept(
        request: request,
        options: options,
        idempotent: true,
        action: {
          (r: SearchPublicKgRequest, o: GoogleCloudGax.RequestOptions) async throws
            -> GoogleCloudEnterpriseKnowledgeGraphV1.SearchPublicKgResponse
          in
          return try await self.inner.searchPublicKg(request: r, options: o)
        })
    }
  }
}
