// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
import GoogleRpc
@_spi(GoogleCloudInternal) import GoogleWKT

/// Entity reconciliation job message.
public struct EntityReconciliationJob: Codable, Equatable, GoogleWKT._AnyPackable,
  Sendable
{
  /// Output only. Resource name of the EntityReconciliationJob.
  public var name: Swift.String = Swift.String()

  /// Required. Information about the input BigQuery tables.
  public var inputConfig: InputConfig? = nil

  /// Required. The desired output location.
  public var outputConfig: OutputConfig? = nil

  /// Output only. The detailed state of the job.
  public var state: JobState = JobState()

  /// Output only. Only populated when the job's state is JOB_STATE_FAILED or
  /// JOB_STATE_CANCELLED.
  public var error: GoogleRpc.Status? = nil

  /// Output only. Time when the EntityReconciliationJob was created.
  public var createTime: GoogleWKT.Timestamp? = nil

  /// Output only. Time when the EntityReconciliationJob entered any of the
  /// following states: `JOB_STATE_SUCCEEDED`, `JOB_STATE_FAILED`,
  /// `JOB_STATE_CANCELLED`.
  public var endTime: GoogleWKT.Timestamp? = nil

  /// Output only. Time when the EntityReconciliationJob was most recently
  /// updated.
  public var updateTime: GoogleWKT.Timestamp? = nil

  /// Optional. Recon configs to adjust the clustering behavior.
  public var reconConfig: ReconConfig? = nil

  @_spi(GoogleCloudInternal) public var _unknownFields: GoogleWKT._UnknownFields = .init()

  /// Initialize a new instance of `EntityReconciliationJob`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = EntityReconciliationJob().with { $0.name = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  private struct CodingKeys: CodingKey {
    var stringValue: Swift.String
    var intValue: Swift.Int? { nil }
    init(stringValue: Swift.String) { self.stringValue = stringValue }
    init?(intValue: Swift.Int) { nil }

    static let name = CodingKeys(stringValue: "name")
    static let inputConfig = CodingKeys(stringValue: "inputConfig")
    static let outputConfig = CodingKeys(stringValue: "outputConfig")
    static let state = CodingKeys(stringValue: "state")
    static let error = CodingKeys(stringValue: "error")
    static let createTime = CodingKeys(stringValue: "createTime")
    static let endTime = CodingKeys(stringValue: "endTime")
    static let updateTime = CodingKeys(stringValue: "updateTime")
    static let reconConfig = CodingKeys(stringValue: "reconConfig")

    static let _knownKeys: Set<Swift.String> = [
      "name",
      "inputConfig",
      "outputConfig",
      "state",
      "error",
      "createTime",
      "endTime",
      "updateTime",
      "reconConfig",
    ]
  }

  public init(from decoder: Decoder) throws {
    let container = try decoder.container(keyedBy: CodingKeys.self)
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .name) {
      self.name = value
    }
    self.inputConfig = try container.decodeIfPresent(InputConfig.self, forKey: .inputConfig)
    self.outputConfig = try container.decodeIfPresent(OutputConfig.self, forKey: .outputConfig)
    if let value = try container.decodeIfPresent(JobState.self, forKey: .state) {
      self.state = value
    }
    self.error = try container.decodeIfPresent(GoogleRpc.Status.self, forKey: .error)
    self.createTime = try container.decodeIfPresent(GoogleWKT.Timestamp.self, forKey: .createTime)
    self.endTime = try container.decodeIfPresent(GoogleWKT.Timestamp.self, forKey: .endTime)
    self.updateTime = try container.decodeIfPresent(GoogleWKT.Timestamp.self, forKey: .updateTime)
    self.reconConfig = try container.decodeIfPresent(ReconConfig.self, forKey: .reconConfig)
    for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
      self._unknownFields.json[key.stringValue] = try container.decode(
        GoogleWKT.Value.self, forKey: key)
    }
  }

  public func encode(to encoder: Encoder) throws {
    var container = encoder.container(keyedBy: CodingKeys.self)
    try container.encode(self.name, forKey: .name)
    try container.encodeIfPresent(self.inputConfig, forKey: .inputConfig)
    try container.encodeIfPresent(self.outputConfig, forKey: .outputConfig)
    try container.encode(self.state, forKey: .state)
    try container.encodeIfPresent(self.error, forKey: .error)
    try container.encodeIfPresent(self.createTime, forKey: .createTime)
    try container.encodeIfPresent(self.endTime, forKey: .endTime)
    try container.encodeIfPresent(self.updateTime, forKey: .updateTime)
    try container.encodeIfPresent(self.reconConfig, forKey: .reconConfig)
    for (key, value) in self._unknownFields.json {
      try container.encode(value, forKey: CodingKeys(stringValue: key))
    }
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.enterpriseknowledgegraph.v1.EntityReconciliationJob"
  }
  public init(fromAny any: GoogleWKT.`Any`) throws {
    self = try GoogleWKT._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleWKT.Struct {
    return try GoogleWKT._slowAnySerialize(message: self)
  }
}
