// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
@_spi(GoogleCloudInternal) import GoogleCloudWkt
import GoogleRpc

/// Entity reconciliation job message.
public struct EntityReconciliationJob: Codable, Equatable, GoogleCloudWkt._AnyPackable,
  Sendable
{
  /// Output only. Resource name of the EntityReconciliationJob.
  public var name: Swift.String = Swift.String()

  /// Required. Information about the input BigQuery tables.
  public var inputConfig: InputConfig? = nil

  /// Required. The desired output location.
  public var outputConfig: OutputConfig? = nil

  /// Output only. The detailed state of the job.
  public var state: JobState = JobState()

  /// Output only. Only populated when the job's state is JOB_STATE_FAILED or
  /// JOB_STATE_CANCELLED.
  public var error: GoogleRpc.Status? = nil

  /// Output only. Time when the EntityReconciliationJob was created.
  public var createTime: GoogleCloudWkt.Timestamp? = nil

  /// Output only. Time when the EntityReconciliationJob entered any of the
  /// following states: `JOB_STATE_SUCCEEDED`, `JOB_STATE_FAILED`,
  /// `JOB_STATE_CANCELLED`.
  public var endTime: GoogleCloudWkt.Timestamp? = nil

  /// Output only. Time when the EntityReconciliationJob was most recently
  /// updated.
  public var updateTime: GoogleCloudWkt.Timestamp? = nil

  /// Optional. Recon configs to adjust the clustering behavior.
  public var reconConfig: ReconConfig? = nil

  /// Initialize a new instance of `EntityReconciliationJob`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = EntityReconciliationJob().with { $0.name = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.enterpriseknowledgegraph.v1.EntityReconciliationJob"
  }
  public init(fromAny any: GoogleCloudWkt.`Any`) throws {
    self = try GoogleCloudWkt._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleCloudWkt.Struct {
    return try GoogleCloudWkt._slowAnySerialize(message: self)
  }
}
