// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
@_spi(GoogleCloudInternal) import GoogleCloudWKT

/// The desired input location and metadata.
public struct InputConfig: Codable, Equatable, GoogleCloudWKT._AnyPackable,
  Sendable
{
  /// Set of input BigQuery tables.
  public var bigqueryInputConfigs: [BigQueryInputConfig] = []

  /// Entity type
  public var entityType: InputConfig.EntityType = InputConfig.EntityType()

  /// Optional. Provide the bigquery table containing the previous results if
  /// cluster ID stability is desired. Format is
  /// `projects/*/datasets/*/tables/*`.
  public var previousResultBigqueryTable: Swift.String = Swift.String()

  /// Initialize a new instance of `InputConfig`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = InputConfig().with { $0.bigqueryInputConfigs = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  /// The type of entities we will support. Currently, we only support people,
  /// establishment, property, and product types. If the type is
  /// unspecified, it will be generic type.
  public enum EntityType: Codable, Equatable, Sendable {
    /// The default value.
    case unspecified
    /// People entity.
    @available(*, deprecated)
    case people
    /// Establishment entity.
    @available(*, deprecated)
    case establishment
    /// Property entity. e.g. real estate property.
    @available(*, deprecated)
    case property
    /// Product entity.
    case product
    /// Organization entity.
    case organization
    /// Local Business entity.
    case localBusiness
    /// Person entity.
    case person
    /// Encodes an unknown integer value.
    ///
    /// The most common cause for an unknown values is for the service to send
    /// a value unknown to the library. We recommend you update your library to
    /// the latest version.
    case unknownIntValue(Int)
    /// Encodes an unknown string value.
    ///
    /// The most common cause for an unknown values is for the service to send
    /// a value unknown to the library. We recommend you update your library to
    /// the latest version.
    case unknownStringValue(String)

    public init() {
      self = .unspecified
    }

    /// Returns the integer value associated with the enumeration.
    ///
    /// If the enumeration was initialized with an unknown string value, this returns `nil`.
    public var intValue: Int? {
      switch self {
      case .unspecified: return 0
      case .people: return 1
      case .establishment: return 2
      case .property: return 3
      case .product: return 4
      case .organization: return 5
      case .localBusiness: return 6
      case .person: return 7
      case .unknownIntValue(let v): return v
      case .unknownStringValue: return nil
      }
    }

    /// Returns the string value (or name) associated with the enumeration.
    ///
    /// If the enumeration was initialized with an unknown integer value, this returns `nil`.
    public var stringValue: Swift.String? {
      switch self {
      case .unspecified: return "ENTITY_TYPE_UNSPECIFIED"
      case .people: return "PEOPLE"
      case .establishment: return "ESTABLISHMENT"
      case .property: return "PROPERTY"
      case .product: return "PRODUCT"
      case .organization: return "ORGANIZATION"
      case .localBusiness: return "LOCAL_BUSINESS"
      case .person: return "PERSON"
      case .unknownIntValue: return nil
      case .unknownStringValue(let v): return v
      }
    }

    /// Initialize from a string value.
    ///
    /// If the value is unknown, this initializes to [`unknownStringValue`](doc:EntityType/unknownStringValue(_:)).
    public init(stringValue: Swift.String) {
      switch stringValue {
      case "ENTITY_TYPE_UNSPECIFIED": self = .unspecified
      case "PEOPLE": self = .people
      case "ESTABLISHMENT": self = .establishment
      case "PROPERTY": self = .property
      case "PRODUCT": self = .product
      case "ORGANIZATION": self = .organization
      case "LOCAL_BUSINESS": self = .localBusiness
      case "PERSON": self = .person
      default: self = .unknownStringValue(stringValue)
      }
    }

    /// Initialize from an integer value.
    ///
    /// If the value is unknown, this initializes to [`unknownIntValue`](doc:EntityType/unknownIntValue(_:)).
    public init(intValue: Int) {
      switch intValue {
      case 0: self = .unspecified
      case 1: self = .people
      case 2: self = .establishment
      case 3: self = .property
      case 4: self = .product
      case 5: self = .organization
      case 6: self = .localBusiness
      case 7: self = .person
      default: self = .unknownIntValue(intValue)
      }
    }

    public init(from decoder: Decoder) throws {
      let container = try decoder.singleValueContainer()
      if let v = try? container.decode(Int.self) {
        self.init(intValue: v)
        return
      }
      if let s = try? container.decode(String.self) {
        if let v = Int(s) {
          self.init(intValue: v)
        } else {
          self.init(stringValue: s)
        }
        return
      }
      throw DecodingError.dataCorruptedError(
        in: container, debugDescription: "Expected enum value, must be integer or string.")
    }

    public func encode(to encoder: Encoder) throws {
      var container = encoder.singleValueContainer()
      switch self {
      case .unspecified: return try container.encode(0)
      case .people: return try container.encode(1)
      case .establishment: return try container.encode(2)
      case .property: return try container.encode(3)
      case .product: return try container.encode(4)
      case .organization: return try container.encode(5)
      case .localBusiness: return try container.encode(6)
      case .person: return try container.encode(7)
      case .unknownIntValue(let v): return try container.encode(v)
      case .unknownStringValue(let v): return try container.encode(v)
      }
    }
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.enterpriseknowledgegraph.v1.InputConfig"
  }
  public init(fromAny any: GoogleCloudWKT.`Any`) throws {
    self = try GoogleCloudWKT._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleCloudWKT.Struct {
    return try GoogleCloudWKT._slowAnySerialize(message: self)
  }
}
