// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation

/// Describes the state of a job.
public enum JobState: Codable, Equatable, Sendable {
  /// The job state is unspecified.
  case unspecified
  /// The job is in progress.
  case running
  /// The job completed successfully.
  case succeeded
  /// The job failed.
  case failed
  /// The job has been cancelled.
  case cancelled
  /// Entity Recon API: The knowledge extraction job is running.
  case knowledgeExtraction
  /// Entity Recon API: The preprocessing job is running.
  case reconPreprocessing
  /// Entity Recon API: The clustering job is running.
  case clustering
  /// Entity Recon API: The exporting clusters job is running.
  case exportingClusters
  /// The service is preparing to run the job.
  case pending
  /// Encodes an unknown integer value.
  ///
  /// The most common cause for an unknown values is for the service to send
  /// a value unknown to the library. We recommend you update your library to
  /// the latest version.
  case unknownIntValue(Int)
  /// Encodes an unknown string value.
  ///
  /// The most common cause for an unknown values is for the service to send
  /// a value unknown to the library. We recommend you update your library to
  /// the latest version.
  case unknownStringValue(String)

  public init() {
    self = .unspecified
  }

  /// Returns the integer value associated with the enumeration.
  ///
  /// If the enumeration was initialized with an unknown string value, this returns `nil`.
  public var intValue: Int? {
    switch self {
    case .unspecified: return 0
    case .running: return 1
    case .succeeded: return 2
    case .failed: return 3
    case .cancelled: return 4
    case .knowledgeExtraction: return 5
    case .reconPreprocessing: return 6
    case .clustering: return 7
    case .exportingClusters: return 8
    case .pending: return 9
    case .unknownIntValue(let v): return v
    case .unknownStringValue: return nil
    }
  }

  /// Returns the string value (or name) associated with the enumeration.
  ///
  /// If the enumeration was initialized with an unknown integer value, this returns `nil`.
  public var stringValue: Swift.String? {
    switch self {
    case .unspecified: return "JOB_STATE_UNSPECIFIED"
    case .running: return "JOB_STATE_RUNNING"
    case .succeeded: return "JOB_STATE_SUCCEEDED"
    case .failed: return "JOB_STATE_FAILED"
    case .cancelled: return "JOB_STATE_CANCELLED"
    case .knowledgeExtraction: return "JOB_STATE_KNOWLEDGE_EXTRACTION"
    case .reconPreprocessing: return "JOB_STATE_RECON_PREPROCESSING"
    case .clustering: return "JOB_STATE_CLUSTERING"
    case .exportingClusters: return "JOB_STATE_EXPORTING_CLUSTERS"
    case .pending: return "JOB_STATE_PENDING"
    case .unknownIntValue: return nil
    case .unknownStringValue(let v): return v
    }
  }

  /// Initialize from a string value.
  ///
  /// If the value is unknown, this initializes to [`unknownStringValue`](doc:JobState/unknownStringValue(_:)).
  public init(stringValue: Swift.String) {
    switch stringValue {
    case "JOB_STATE_UNSPECIFIED": self = .unspecified
    case "JOB_STATE_PENDING": self = .pending
    case "JOB_STATE_RUNNING": self = .running
    case "JOB_STATE_SUCCEEDED": self = .succeeded
    case "JOB_STATE_FAILED": self = .failed
    case "JOB_STATE_CANCELLED": self = .cancelled
    case "JOB_STATE_KNOWLEDGE_EXTRACTION": self = .knowledgeExtraction
    case "JOB_STATE_RECON_PREPROCESSING": self = .reconPreprocessing
    case "JOB_STATE_CLUSTERING": self = .clustering
    case "JOB_STATE_EXPORTING_CLUSTERS": self = .exportingClusters
    default: self = .unknownStringValue(stringValue)
    }
  }

  /// Initialize from an integer value.
  ///
  /// If the value is unknown, this initializes to [`unknownIntValue`](doc:JobState/unknownIntValue(_:)).
  public init(intValue: Int) {
    switch intValue {
    case 0: self = .unspecified
    case 1: self = .running
    case 2: self = .succeeded
    case 3: self = .failed
    case 4: self = .cancelled
    case 5: self = .knowledgeExtraction
    case 6: self = .reconPreprocessing
    case 7: self = .clustering
    case 8: self = .exportingClusters
    case 9: self = .pending
    default: self = .unknownIntValue(intValue)
    }
  }

  public init(from decoder: Decoder) throws {
    let container = try decoder.singleValueContainer()
    if let v = try? container.decode(Int.self) {
      self.init(intValue: v)
      return
    }
    if let s = try? container.decode(String.self) {
      if let v = Int(s) {
        self.init(intValue: v)
      } else {
        self.init(stringValue: s)
      }
      return
    }
    throw DecodingError.dataCorruptedError(
      in: container, debugDescription: "Expected enum value, must be integer or string.")
  }

  public func encode(to encoder: Encoder) throws {
    var container = encoder.singleValueContainer()
    switch self {
    case .unspecified: return try container.encode(0)
    case .running: return try container.encode(1)
    case .succeeded: return try container.encode(2)
    case .failed: return try container.encode(3)
    case .cancelled: return try container.encode(4)
    case .knowledgeExtraction: return try container.encode(5)
    case .reconPreprocessing: return try container.encode(6)
    case .clustering: return try container.encode(7)
    case .exportingClusters: return try container.encode(8)
    case .pending: return try container.encode(9)
    case .unknownIntValue(let v): return try container.encode(v)
    case .unknownStringValue(let v): return try container.encode(v)
    }
  }
}
