// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
@_spi(GoogleCloudInternal) import GoogleWKT

/// Recon configs
public struct ReconConfig: Codable, Equatable, GoogleWKT._AnyPackable,
  Sendable
{
  /// Extra options that affect entity clustering behavior.
  public var options: ReconConfig.Options? = nil

  /// Model Configs
  public var modelConfig: ReconConfig.ModelConfig? = nil

  /// Choice of clustering algorithm. Default is ConnectedComponentsConfig.
  public var clusteringConfig: OneOf_ClusteringConfig? = nil

  @_spi(GoogleCloudInternal) public var _unknownFields: GoogleWKT._UnknownFields = .init()

  /// Initialize a new instance of `ReconConfig`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = ReconConfig().with { $0.connectedComponentsConfig = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  private struct CodingKeys: CodingKey {
    var stringValue: Swift.String
    var intValue: Swift.Int? { nil }
    init(stringValue: Swift.String) { self.stringValue = stringValue }
    init?(intValue: Swift.Int) { nil }

    static let connectedComponentsConfig = CodingKeys(stringValue: "connectedComponentsConfig")
    static let affinityClusteringConfig = CodingKeys(stringValue: "affinityClusteringConfig")
    static let options = CodingKeys(stringValue: "options")
    static let modelConfig = CodingKeys(stringValue: "modelConfig")

    static let _knownKeys: Set<Swift.String> = [
      "connectedComponentsConfig",
      "affinityClusteringConfig",
      "options",
      "modelConfig",
    ]
  }

  public init(from decoder: Decoder) throws {
    let container = try decoder.container(keyedBy: CodingKeys.self)
    self.options = try container.decodeIfPresent(ReconConfig.Options.self, forKey: .options)
    self.modelConfig = try container.decodeIfPresent(
      ReconConfig.ModelConfig.self, forKey: .modelConfig)

    var clusteringConfig: OneOf_ClusteringConfig? = nil
    let clusteringConfigCheckAndSet = {
      if clusteringConfig != nil {
        throw DecodingError.dataCorrupted(
          DecodingError.Context(
            codingPath: decoder.codingPath,
            debugDescription: "Multiple values set for oneof 'clusteringConfig'"))
      }
      clusteringConfig = $0
    }
    if let connectedComponentsConfig = try container.decodeIfPresent(
      ConnectedComponentsConfig?.self, forKey: .connectedComponentsConfig)
    {
      try clusteringConfigCheckAndSet(.connectedComponentsConfig(connectedComponentsConfig))
    }
    if let affinityClusteringConfig = try container.decodeIfPresent(
      AffinityClusteringConfig?.self, forKey: .affinityClusteringConfig)
    {
      try clusteringConfigCheckAndSet(.affinityClusteringConfig(affinityClusteringConfig))
    }
    self.clusteringConfig = clusteringConfig
    for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
      self._unknownFields.json[key.stringValue] = try container.decode(
        GoogleWKT.Value.self, forKey: key)
    }
  }

  public func encode(to encoder: Encoder) throws {
    var container = encoder.container(keyedBy: CodingKeys.self)
    try container.encodeIfPresent(self.options, forKey: .options)
    try container.encodeIfPresent(self.modelConfig, forKey: .modelConfig)

    if let choice = self.clusteringConfig {
      switch choice {
      case .connectedComponentsConfig(let value):
        try container.encode(value, forKey: .connectedComponentsConfig)
      case .affinityClusteringConfig(let value):
        try container.encode(value, forKey: .affinityClusteringConfig)
      }
    }
    for (key, value) in self._unknownFields.json {
      try container.encode(value, forKey: CodingKeys(stringValue: key))
    }
  }

  /// Options for experimental changes on entity clustering behavior.
  public struct Options: Codable, Equatable, GoogleWKT._AnyPackable,
    Sendable
  {
    /// If true, separate clusters by their geographic region (from geocoding).
    /// Uses the following entity features:
    ///
    /// - schema.org/addressLocality
    /// - schema.org/addressRegion
    /// - schema.org/addressCountry
    /// Warning: processing will no longer be regionalized!
    public var enableGeocodingSeparation: Swift.Bool = Swift.Bool()

    @_spi(GoogleCloudInternal) public var _unknownFields: GoogleWKT._UnknownFields = .init()

    /// Initialize a new instance of `Options`.
    public init() {}

    /// Use `config` to return a new instance of this object, with some fields updated.
    ///
    /// Commonly used to initialize the value, for example:
    ///
    /// ```
    /// let value = Options().with { $0.enableGeocodingSeparation = ... }
    /// ```
    public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
      var copy = self
      try config(&copy)
      return copy
    }

    private struct CodingKeys: CodingKey {
      var stringValue: Swift.String
      var intValue: Swift.Int? { nil }
      init(stringValue: Swift.String) { self.stringValue = stringValue }
      init?(intValue: Swift.Int) { nil }

      static let enableGeocodingSeparation = CodingKeys(stringValue: "enableGeocodingSeparation")

      static let _knownKeys: Set<Swift.String> = [
        "enableGeocodingSeparation"
      ]
    }

    public init(from decoder: Decoder) throws {
      let container = try decoder.container(keyedBy: CodingKeys.self)
      if let value = try container.decodeIfPresent(
        Swift.Bool.self, forKey: .enableGeocodingSeparation)
      {
        self.enableGeocodingSeparation = value
      }
      for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
        self._unknownFields.json[key.stringValue] = try container.decode(
          GoogleWKT.Value.self, forKey: key)
      }
    }

    public func encode(to encoder: Encoder) throws {
      var container = encoder.container(keyedBy: CodingKeys.self)
      try container.encode(self.enableGeocodingSeparation, forKey: .enableGeocodingSeparation)
      for (key, value) in self._unknownFields.json {
        try container.encode(value, forKey: CodingKeys(stringValue: key))
      }
    }

    public static var _anyTypeUrl: Swift.String {
      return "type.googleapis.com/google.cloud.enterpriseknowledgegraph.v1.ReconConfig.Options"
    }
    public init(fromAny any: GoogleWKT.`Any`) throws {
      self = try GoogleWKT._slowAnyDeserialize(Self.self, from: any)
    }
    public func _pack() throws -> GoogleWKT.Struct {
      return try GoogleWKT._slowAnySerialize(message: self)
    }
  }

  /// Model Configs
  public struct ModelConfig: Codable, Equatable, GoogleWKT._AnyPackable,
    Sendable
  {
    /// Model name. Refer to external documentation for valid names.
    /// If unspecified, it defaults to the one mentioned in the documentation.
    public var modelName: Swift.String = Swift.String()

    /// Model version tag. Refer to external documentation for valid tags.
    /// If unspecified, it defaults to the one mentioned in the documentation.
    public var versionTag: Swift.String = Swift.String()

    @_spi(GoogleCloudInternal) public var _unknownFields: GoogleWKT._UnknownFields = .init()

    /// Initialize a new instance of `ModelConfig`.
    public init() {}

    /// Use `config` to return a new instance of this object, with some fields updated.
    ///
    /// Commonly used to initialize the value, for example:
    ///
    /// ```
    /// let value = ModelConfig().with { $0.modelName = ... }
    /// ```
    public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
      var copy = self
      try config(&copy)
      return copy
    }

    private struct CodingKeys: CodingKey {
      var stringValue: Swift.String
      var intValue: Swift.Int? { nil }
      init(stringValue: Swift.String) { self.stringValue = stringValue }
      init?(intValue: Swift.Int) { nil }

      static let modelName = CodingKeys(stringValue: "modelName")
      static let versionTag = CodingKeys(stringValue: "versionTag")

      static let _knownKeys: Set<Swift.String> = [
        "modelName",
        "versionTag",
      ]
    }

    public init(from decoder: Decoder) throws {
      let container = try decoder.container(keyedBy: CodingKeys.self)
      if let value = try container.decodeIfPresent(Swift.String.self, forKey: .modelName) {
        self.modelName = value
      }
      if let value = try container.decodeIfPresent(Swift.String.self, forKey: .versionTag) {
        self.versionTag = value
      }
      for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
        self._unknownFields.json[key.stringValue] = try container.decode(
          GoogleWKT.Value.self, forKey: key)
      }
    }

    public func encode(to encoder: Encoder) throws {
      var container = encoder.container(keyedBy: CodingKeys.self)
      try container.encode(self.modelName, forKey: .modelName)
      try container.encode(self.versionTag, forKey: .versionTag)
      for (key, value) in self._unknownFields.json {
        try container.encode(value, forKey: CodingKeys(stringValue: key))
      }
    }

    public static var _anyTypeUrl: Swift.String {
      return "type.googleapis.com/google.cloud.enterpriseknowledgegraph.v1.ReconConfig.ModelConfig"
    }
    public init(fromAny any: GoogleWKT.`Any`) throws {
      self = try GoogleWKT._slowAnyDeserialize(Self.self, from: any)
    }
    public func _pack() throws -> GoogleWKT.Struct {
      return try GoogleWKT._slowAnySerialize(message: self)
    }
  }

  /// Choice of clustering algorithm. Default is ConnectedComponentsConfig.
  public enum OneOf_ClusteringConfig: Codable, Equatable, Sendable {
    /// Configs for connected components.
    indirect case connectedComponentsConfig(ConnectedComponentsConfig?)
    /// Configs for affinity clustering.
    indirect case affinityClusteringConfig(AffinityClusteringConfig?)
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.enterpriseknowledgegraph.v1.ReconConfig"
  }
  public init(fromAny any: GoogleWKT.`Any`) throws {
    self = try GoogleWKT._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleWKT.Struct {
    return try GoogleWKT._slowAnySerialize(message: self)
  }
}
